
project_id = "jlyxtvwnjrxrdvxnneii"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.selar-webhook]
verify_jwt = false

[functions.generate-report]
verify_jwt = true

[functions.ai-helper]
verify_jwt = true
